import test from 'node:test';
import assert from 'node:assert/strict';
import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  readdirSync,
  rmSync,
  openSync,
  closeSync,
  constants
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import ts from 'typescript';
import { snapshotGeneratedArtifacts } from './lib/generated-artifact-snapshot.mjs';
import {
  prepareProcessSourceMapChain,
  convertProcessSourceMapChain
} from './lib/process-source-map-chain.mjs';
import { validateNativeSourceMap } from './lib/native-v8-conversion.mjs';

const hash = (code) => createHash('sha256').update(code).digest('hex');
const persistence = new URL('./lib/process-script-persistence.mjs', import.meta.url).href;

function observe(
  t,
  {
    sameUrl = false,
    intermediateMapping,
    cycle = false,
    loaderTsx = false,
    lineEnding = '\n',
    mapPadding = 0,
    generatedEnding = '\n'
  } = {}
) {
  const root = mkdtempSync(join(tmpdir(), 'cvg map chain ç-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  for (const path of ['apps', 'packages', 'raw']) mkdirSync(join(root, path));
  const original = join(root, 'packages/original space.ts');
  const generated = join(root, 'packages/intermediate space.js');
  const executed = sameUrl ? generated : join(root, 'packages/observed.js');
  const originalUrl = pathToFileURL(original).href;
  const generatedUrl = pathToFileURL(generated).href;
  const url = pathToFileURL(executed).href;
  const source = (
    (loaderTsx ? 'export ' : '') +
    'function choose(value: boolean): number { return value ? 1 : 2; }\n' +
    (loaderTsx ? 'export ' : '') +
    'function neverCalled(): number { return 3; }\nglobalThis.__choice = choose(true);\n'
  ).replaceAll('\n', lineEnding);
  writeFileSync(original, source);
  const first = ts.transpileModule(source, {
    fileName: original,
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      sourceMap: true,
      inlineSources: true
    }
  });
  const map = JSON.parse(first.sourceMapText);
  map.sources = [originalUrl];
  if (intermediateMapping !== undefined) map.mappings = intermediateMapping;
  const intermediate = first.outputText.replace(
    /sourceMappingURL=[^\s]+/,
    'sourceMappingURL=intermediate%20space.js.map'
  );
  if (cycle) {
    map.sources = [generatedUrl];
    map.sourcesContent = [intermediate];
    map.mappings = 'AAAA';
  }
  writeFileSync(generated, intermediate);
  writeFileSync(generated + '.map', JSON.stringify(map) + ' '.repeat(mapPadding));
  // The second transform maps to the exact frozen generated bytes. Its runtime
  // URL may equal the intermediate URL, as with real loader transformations.
  const second = ts.transpileModule(intermediate, {
    fileName: generated,
    compilerOptions: { target: ts.ScriptTarget.ES2015, sourceMap: true, inlineSources: true }
  });
  const topMap = JSON.parse(second.sourceMapText);
  topMap.sources = [generatedUrl];
  const code = (
    second.outputText.replace(/\/\/[#@]\s*sourceMappingURL=[^\n]*/g, (comment) =>
      ' '.repeat(comment.length)
    ) +
    '\n//# sourceMappingURL=data:application/json;base64,' +
    Buffer.from(JSON.stringify(topMap)).toString('base64')
  ).replaceAll('\n', generatedEnding);
  const before = snapshotGeneratedArtifacts(root);
  const files = { ...before.files, [originalUrl]: source };
  const frozenHashes = { ...before.frozenHashes, [originalUrl]: hash(source) };
  const driver = join(root, 'driver.mjs');
  const execute = loaderTsx
    ? `await import(${JSON.stringify(url)});`
    : `runInThisContext(${JSON.stringify(code)},{filename:${JSON.stringify(url)}});`;
  if (loaderTsx) writeFileSync(join(root, 'package.json'), '{"type":"module"}');
  writeFileSync(
    driver,
    `import{runInThisContext}from'node:vm';import{takeCoverage}from'node:v8';import{startProcessScriptPersistence}from${JSON.stringify(persistence)};const c=await startProcessScriptPersistence({root:${JSON.stringify(root)}});${execute}if(globalThis.__choice!==1)throw Error('wrong result');c.flush();takeCoverage();process.on('exit',()=>c.flush());`
  );
  const fd = openSync(join(root, 'raw'), constants.O_RDONLY | constants.O_DIRECTORY);
  let child;
  try {
    child = spawnSync(process.execPath, loaderTsx ? ['--import', 'tsx/esm', driver] : [driver], {
      env: {
        PATH: process.env.PATH,
        NODE_ENV: 'test',
        CVG_CRITICAL_PROCESS_COVERAGE: '1',
        NODE_V8_COVERAGE: `/proc/${process.pid}/fd/${fd}`
      },
      encoding: 'utf8',
      timeout: 10000,
      maxBuffer: 1024 * 1024
    });
  } finally {
    closeSync(fd);
  }
  assert.equal(child.status, 0, child.stderr);
  assert.deepEqual(snapshotGeneratedArtifacts(root), before);
  const raw = readdirSync(join(root, 'raw')).map((name) =>
    JSON.parse(readFileSync(join(root, 'raw', name)))
  );
  const observation = raw.find((r) => r.kind === 'executed-script-observation' && r.url === url);
  assert.ok(observation, 'inspector observation must exist');
  if (!loaderTsx) assert.equal(observation.code, code);
  const report = raw.find((r) =>
    r.result?.some(
      (s) =>
        s.scriptId === observation.scriptId &&
        s.url === url &&
        s.functions.some((f) => f.functionName === 'choose' && f.ranges[0].count === 1)
    )
  );
  assert.ok(report, 'real V8 choose interval must exist');
  return {
    original,
    originalUrl,
    generatedUrl,
    input: {
      observation,
      coverage: report.result.find((s) => s.scriptId === observation.scriptId && s.url === url),
      pid: observation.pid,
      threadId: observation.threadId,
      files,
      frozenHashes,
      cachedMap: report['source-map-cache']?.[url]?.data
    },
    options: { terminalHashes: { [originalUrl]: hash(source) } }
  };
}

for (const [sameUrl, loaderTsx] of [
  [false, false],
  [true, false],
  [true, true]
]) {
  test(`composes real transforms to frozen TypeScript, same URL=${sameUrl}, tsx=${loaderTsx}`, async (t) => {
    const { original, originalUrl, generatedUrl, input, options } = observe(t, {
      sameUrl,
      loaderTsx
    });
    const before = JSON.stringify({ input, options });
    const prepared = prepareProcessSourceMapChain(input, options);
    assert.deepEqual(prepared.sourceMap.sources, [originalUrl]);
    // This installed tsx delegates already-valid ESM JavaScript unchanged.
    // The explicit VM transformations above exercise the two-stage chain.
    assert.equal(prepared.stages.length, loaderTsx ? 1 : 2);
    if (loaderTsx) assert.equal(input.observation.code, input.files[generatedUrl]);
    if (sameUrl && !loaderTsx) {
      assert.equal(prepared.stages[0].url, prepared.stages[1].url);
      assert.notEqual(prepared.stages[0].codeSha256, prepared.stages[1].codeSha256);
    }
    assert.equal(prepared.coverage, input.coverage);
    assert.equal(prepared.code, input.observation.code);
    const converted = await convertProcessSourceMapChain(input, options);
    assert.deepEqual(Object.keys(converted), [original]);
    const entry = converted[original];
    const id = (name) => Object.keys(entry.fnMap).find((id) => entry.fnMap[id].name === name);
    assert.equal(entry.f[id('choose')], 1);
    assert.equal(entry.f[id('neverCalled')], 0);
    assert.ok(Object.values(entry.b).flat().includes(0));
    assert.equal(JSON.stringify({ input, options }), before);
    if (!loaderTsx)
      assert.throws(
        () => prepareProcessSourceMapChain(input, { ...options, maxStages: 1 }),
        /stage limit/
      );
    assert.throws(
      () => prepareProcessSourceMapChain(input, { ...options, maxMapBytes: 1 }),
      /byte limit/
    );
    assert.throws(
      () => prepareProcessSourceMapChain(input, { terminalHashes: {} }),
      /Unexpected token|unambiguous/
    );
    assert.throws(
      () =>
        prepareProcessSourceMapChain(input, { terminalHashes: { [originalUrl]: '0'.repeat(64) } }),
      /terminal original/
    );
    const missing = { ...input.frozenHashes };
    delete missing[generatedUrl];
    assert.throws(
      () => prepareProcessSourceMapChain({ ...input, frozenHashes: missing }, options),
      /unbound/
    );
  });
}

test('rejects invalid intermediate coordinates before composition can erase them', (t) => {
  const { input, options } = observe(t, {
    intermediateMapping: 'AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA'
  });
  assert.throws(
    () => prepareProcessSourceMapChain(input, options),
    /invalid generated source map coordinates/
  );
});

for (const sameUrl of [false, true]) {
  test(`rejects a cyclic frozen stage with real observed code, same URL=${sameUrl}`, (t) => {
    const { input, options } = observe(t, { sameUrl, cycle: true });
    assert.throws(() => prepareProcessSourceMapChain(input, options), /cyclic source map chain/);
  });
}

for (const mappings of ['g', '!', 'ggggggggggggA', 'AAAA,DAAA']) {
  test(`rejects malformed intermediate VLQ ${JSON.stringify(mappings)}`, (t) => {
    const { input, options } = observe(t, { intermediateMapping: mappings });
    assert.throws(() => prepareProcessSourceMapChain(input, options), /VLQ|coordinates/);
  });
}

test('empty intermediate map cannot yield a certified original', async (t) => {
  const { input, options } = observe(t, { intermediateMapping: '' });
  await assert.rejects(
    convertProcessSourceMapChain(input, options),
    /did not reach terminal|empty/
  );
});

for (const lineEnding of ['\r', '\r\n', '\u2028', '\u2029']) {
  test(`authenticates original line terminator ${JSON.stringify(lineEnding)}`, async (t) => {
    const { input, options, original } = observe(t, { lineEnding });
    const result = await convertProcessSourceMapChain(input, options);
    assert.deepEqual(Object.keys(result), [original]);
    const entry = result[original];
    const never = Object.keys(entry.fnMap).find((id) => entry.fnMap[id].name === 'neverCalled');
    assert.equal(entry.f[never], 0);
    assert.ok(Object.values(entry.b).flat().includes(0));
    assert.ok(Object.values(entry.statementMap).some((loc) => loc.start.line === 3));
  });
  test(`rejects out-of-line original column before remapping ${JSON.stringify(lineEnding)}`, () => {
    const url = 'file:///virtual/original.ts';
    assert.throws(
      () =>
        validateNativeSourceMap({
          code: 'var generatedA = 1;\nvar generatedB = 2;\n',
          sourceMap: { version: 3, names: [], sources: [url], mappings: 'AAAyB;AAAzB' },
          sources: {
            [url]: `var probeA: number = 1;${lineEnding}var probeB: number = 2;${lineEnding}`
          }
        }),
      /invalid original source map coordinates/
    );
  });
}

test('aggregate map budget counts authenticated external JSON whitespace', (t) => {
  const { input, options } = observe(t, { mapPadding: 8192 });
  assert.ok(prepareProcessSourceMapChain(input, options));
  assert.throws(
    () => prepareProcessSourceMapChain(input, { ...options, maxMapBytes: 4096 }),
    /byte limit/
  );
});

function graphInput(reverse = false) {
  const urls = Object.fromEntries(
    ['R', 'A', 'B', 'C', 'T'].map((name) => [name, `file:///virtual/${name}.js`])
  );
  const files = { [urls.T]: 'x();' };
  const mapCode = (sources, bom = false) => {
    const raw = Buffer.concat([
      bom ? Buffer.from([0xef, 0xbb, 0xbf]) : Buffer.alloc(0),
      Buffer.from(JSON.stringify({ version: 3, names: [], sources, mappings: 'AAAA' }))
    ]);
    return {
      code: 'x();\n//# sourceMappingURL=data:application/json;base64,' + raw.toString('base64'),
      raw
    };
  };
  files[urls.C] = mapCode([urls.T]).code;
  files[urls.A] = mapCode([urls.C]).code;
  files[urls.B] = mapCode([urls.A]).code;
  const root = mapCode(reverse ? [urls.B, urls.A] : [urls.A, urls.B]);
  return {
    urls,
    mapCode,
    input: {
      observation: {
        schemaVersion: 1,
        kind: 'executed-script-observation',
        pid: 123,
        threadId: 0,
        scriptId: '1',
        url: urls.R,
        code: root.code,
        sha256: hash(root.code)
      },
      coverage: {
        scriptId: '1',
        url: urls.R,
        functions: [
          {
            functionName: '',
            isBlockCoverage: true,
            ranges: [{ startOffset: 0, endOffset: root.code.length, count: 1 }]
          }
        ]
      },
      pid: 123,
      threadId: 0,
      files,
      frozenHashes: Object.fromEntries(
        Object.entries(files).map(([url, code]) => [url, hash(code)])
      )
    },
    options: { terminalHashes: { [urls.T]: hash(files[urls.T]) } }
  };
}

test('memoized subtree depth is enforced regardless of source ordering', () => {
  // Synthetic graph tests the pure preparation boundary, not observation trust.
  for (const reverse of [false, true]) {
    const { input, options } = graphInput(reverse);
    assert.throws(
      () => prepareProcessSourceMapChain(input, { ...options, maxDepth: 2 }),
      /depth limit/
    );
    assert.ok(prepareProcessSourceMapChain(input, { ...options, maxDepth: 3 }));
  }
});

test('inline map BOM belongs to the authenticated byte count and digest', () => {
  const { input, options, urls, mapCode } = graphInput();
  const { code, raw } = mapCode([urls.T], true);
  input.observation.code = code;
  input.observation.sha256 = hash(code);
  input.coverage.functions[0].ranges[0].endOffset = code.length;
  assert.throws(
    () => prepareProcessSourceMapChain(input, { ...options, maxMapBytes: raw.length - 1 }),
    /byte limit/
  );
  const prepared = prepareProcessSourceMapChain(input, { ...options, maxMapBytes: raw.length });
  assert.equal(prepared.stages[0].mapBytes, raw.length);
  assert.equal(prepared.stages[0].mapSha256, hash(raw));
});

for (const generatedEnding of ['\r\n', '\r', '\u2028', '\u2029']) {
  test(`two-stage real generated terminator ${JSON.stringify(generatedEnding)} retains zero-hit instrumentation`, async (t) => {
    const { input, options, original } = observe(t, { sameUrl: true, generatedEnding });
    const before = JSON.stringify(input);
    const result = (await convertProcessSourceMapChain(input, options))[original];
    const never = Object.keys(result.fnMap).find((id) => result.fnMap[id].name === 'neverCalled');
    assert.notEqual(never, undefined);
    assert.equal(result.f[never], 0);
    assert.equal(result.fnMap[never].loc.start.line, 2);
    assert.ok(Object.values(result.statementMap).some((loc) => loc.start.line === 3));
    assert.ok(Object.values(result.b).flat().includes(0));
    assert.equal(JSON.stringify(input), before);
  });
}
