import type { FastifyPluginAsync } from 'fastify';

import { appointmentsRoutes } from '../modules/appointments/routes.js';
import { agendaConfigRoutes } from '../modules/agendaConfig/routes.js';
import { auditRoutes } from '../modules/audit/routes.js';
import { alertsRoutes } from '../modules/alerts/routes.js';
import { authRoutes } from '../modules/auth/routes.js';
import { bedMapRoutes } from '../modules/bedmap/routes.js';
import { bedsRoutes } from '../modules/beds/routes.js';
import { buildRoutes } from '../modules/build/routes.js';
import { clinicalNotesRoutes } from '../modules/clinicalNotes/routes.js';
import { documentsRoutes } from '../modules/documents/routes.js';
import { encountersRoutes } from '../modules/encounters/routes.js';
import { handoversRoutes } from '../modules/handovers/routes.js';
import { inpatientRoutes } from '../modules/inpatient/routes.js';
import { medicationAdministrationsRoutes } from '../modules/medicationAdministrations/routes.js';
import { medicationDosesRoutes } from '../modules/medicationDoses/routes.js';
import { medicationLogsRoutes } from '../modules/medicationLogs/routes.js';
import { medicationOrdersRoutes } from '../modules/medicationOrders/routes.js';
import { medicationSchedulesRoutes } from '../modules/medicationSchedules/routes.js';
import { wardsRoutes } from '../modules/wards/routes.js';
import { patientsRoutes } from '../modules/patients/routes.js';
import { patientContextRoutes } from '../modules/patientContext/routes.js';
import { rbacRoutes } from '../modules/rbac/routes.js';
import { searchRoutes } from '../modules/search/routes.js';
import { ownersRoutes } from '../modules/owners/routes.js';
import { encounterBillingRoutes } from '../modules/encounterBilling/routes.js';
import { encounterFinancialRoutes } from '../modules/encounterFinancial/routes.js';
import { examsRoutes } from '../modules/exams/routes.js';
import { integrationRoutes } from '../modules/integration/routes.js';
import { productsRoutes } from '../modules/products/routes.js';
import { protocolsRoutes } from '../modules/protocols/routes.js';
import { protocolDiffRoutes } from '../modules/protocolDiff/routes.js';
import { servicesRoutes } from '../modules/services/routes.js';
import { protocolPublishRoutes } from '../modules/protocolPublish/routes.js';
import { protocolReferencesRoutes } from '../modules/protocolReferences/routes.js';
import { protocolVersionsRoutes } from '../modules/protocolVersions/routes.js';
import { systemRoutes } from '../modules/system/routes.js';
import { reportsRoutes } from '../modules/reports/routes.js';
import { metricsRoutes } from '../modules/metrics/routes.js';
import { stockRoutes } from '../modules/stock/routes.js';
import { paymentsRoutes } from '../modules/payments/routes.js';
import { cashRoutes } from '../modules/cash/routes.js';
import { dashboardRoutes } from '../modules/dashboard/routes.js';
import { notificationRoutes } from '../modules/notifications/routes.js';
import { partnersRoutes } from '../modules/partners/routes.js';
import { healthRoutes } from './health.js';

export const apiRoutes: FastifyPluginAsync = async (app) => {
  await app.register(healthRoutes);
  await app.register(systemRoutes);
  await app.register(buildRoutes);
  await app.register(authRoutes, { prefix: '/auth' });
  await app.register(auditRoutes);
  await app.register(alertsRoutes, { prefix: '/alerts' });
  await app.register(rbacRoutes);
  await app.register(clinicalNotesRoutes);
  await app.register(documentsRoutes);
  await app.register(wardsRoutes, { prefix: '/wards' });
  await app.register(bedMapRoutes, { prefix: '/beds' });
  await app.register(bedsRoutes, { prefix: '/beds' });
  await app.register(ownersRoutes, { prefix: '/owners' });
  await app.register(productsRoutes, { prefix: '/products' });
  await app.register(protocolsRoutes, { prefix: '/protocols' });
  await app.register(protocolReferencesRoutes, { prefix: '/protocols' });
  await app.register(protocolDiffRoutes);
  await app.register(protocolPublishRoutes);
  await app.register(protocolVersionsRoutes);
  await app.register(patientsRoutes, { prefix: '/patients' });
  await app.register(encountersRoutes, { prefix: '/encounters' });
  await app.register(encounterBillingRoutes);
  await app.register(encounterFinancialRoutes);
  await app.register(examsRoutes);
  await app.register(integrationRoutes);
  await app.register(inpatientRoutes, { prefix: '/inpatient' });
  await app.register(medicationOrdersRoutes, { prefix: '/medication-orders' });
  await app.register(medicationSchedulesRoutes, { prefix: '/medication-orders' });
  await app.register(medicationAdministrationsRoutes, { prefix: '/medication-administrations' });
  await app.register(medicationDosesRoutes, { prefix: '/medication-doses' });
  await app.register(medicationLogsRoutes, { prefix: '/medication-logs' });
  await app.register(handoversRoutes, { prefix: '/handovers' });
  await app.register(searchRoutes, { prefix: '/search' });
  await app.register(servicesRoutes, { prefix: '/services' });
  await app.register(appointmentsRoutes, { prefix: '/appointments' });
  await app.register(agendaConfigRoutes);
  await app.register(reportsRoutes);
  await app.register(metricsRoutes);
  await app.register(stockRoutes);
  await app.register(paymentsRoutes);
  await app.register(cashRoutes);
  await app.register(dashboardRoutes);
  await app.register(notificationRoutes, { prefix: '/notifications' });
  await app.register(partnersRoutes, { prefix: '/partners' });
  await app.register(patientContextRoutes, { prefix: '/patient-context' });
};
