/**
 * Runtime-light permission catalog shared by the router and the shell.
 *
 * Keep this module free of the visual navigation tree. The router needs the
 * authorization contract before the authenticated layout is loaded, while
 * the layout can defer its heavier labels, keywords and grouping metadata.
 */
export const navigationPermissionCodes: Readonly<Record<string, readonly string[]>> = {
  '/': [],
  '/reception': ['owners.read', 'patients.read'],
  '/appointments': ['scheduling.read'],
  '/counter-sales': ['counter_sale.read'],
  '/sales': ['counter_sale.read'],
  '/packages': ['counter_sale.read'],
  '/queue': ['scheduling.read'],
  '/exam-orders': ['diagnostics.read'],
  '/vaccines-dewormers': ['service.read'],
  '/quotes': ['quote.read'],
  '/loyalty': ['counter_sale.read'],
  '/sales/beta': ['counter_sale.read'],
  '/inpatient': ['inpatient.read'],
  '/inpatient/daily-charges': ['inpatient.read'],
  '/sectors': ['inventory.read'],
  '/patients': ['patients.read'],
  '/owners': ['owners.read'],
  '/services': ['service.read'],
  '/services/import': ['service.write'],
  '/vetus-imports': ['patients.read'],
  '/responsibility-terms': ['service.read'],
  '/breeds': ['service.read'],
  '/species': ['service.read'],
  '/coat-colors': ['service.read'],
  '/customer-groups': ['service.read'],
  '/beds': ['inpatient.read'],
  '/encounters': ['encounters.read'],
  '/medical-records': ['medical-records.read'],
  '/workflow-tasks': ['workflow-tasks.read'],
  '/triage': ['triage.read'],
  '/prescriptions': ['prescriptions.read'],
  '/prescription-executions': ['prescription-executions.read'],
  '/surgery': ['surgery.read'],
  '/discharges': ['discharges.read'],
  '/inpatient/board': ['inpatient.read'],
  '/laboratory/orders': ['diagnostics.read'],
  '/laboratory/results': ['diagnostics.read'],
  '/laboratory/hemograms': ['diagnostics.read'],
  '/laboratory/urinalysis': ['diagnostics.read'],
  '/laboratory/biochemistry': ['diagnostics.read'],
  '/laboratory/equipment': ['diagnostics.read'],
  '/laboratory/report-types': ['diagnostics.read'],
  '/laboratory/hemogram-reference-values': ['diagnostics.read'],
  '/laboratory/biochemistry-reference-values': ['diagnostics.read'],
  '/laboratory': ['diagnostics.read'],
  '/exam-results': ['diagnostics.read'],
  '/diagnostics': ['diagnostics.read'],
  '/inventory/price-consultation': ['inventory.read'],
  '/inventory/nf': ['inventory.read'],
  '/inventory/movements': ['inventory.read'],
  '/inventory/pharmacy': ['inventory.read'],
  '/inventory/validity': ['inventory.read'],
  '/inventory/audit': ['inventory.read'],
  '/inventory/price-audit': ['inventory.read'],
  '/inventory/transfers': ['inventory.read'],
  '/inventory/purchases': ['inventory.read'],
  '/inventory/price-adjustments': ['inventory.read'],
  '/inventory/data-collectors': ['inventory.read'],
  '/products': ['product.read'],
  '/products/import': ['product.write'],
  '/suppliers': ['inventory.read'],
  '/warehouses': ['inventory.read'],
  '/manufacturers': ['inventory.read'],
  '/product-groups': ['inventory.read'],
  '/company-sectors': ['inventory.read'],
  '/measurement-units': ['inventory.read'],
  '/tabelas-de-preco': ['counter_sale.read'],
  '/pontos-de-venda': ['counter_sale.read'],
  '/fiscal/icms': ['fiscal.read'],
  '/fiscal/ipi': ['fiscal.read'],
  '/fiscal/pis': ['fiscal.read'],
  '/fiscal/cofins': ['fiscal.read'],
  '/fiscal/cfop': ['fiscal.read'],
  '/fiscal/nfse': ['fiscal.read'],
  '/fiscal/icms-matrix': ['fiscal.read'],
  '/fiscal/ibs-cbs': ['fiscal.read'],
  '/cash': ['billing.read'],
  '/billing': ['billing.read'],
  '/finance/accounts-payable': ['billing.read'],
  '/finance/reconciliation': ['billing.read'],
  '/finance/advance-payments': ['billing.read'],
  '/finance/card-accounts': ['billing.read'],
  '/finance/cheques': ['billing.read'],
  '/finance/cash-flow': ['billing.read'],
  '/dashboards/curve-abc-clients': ['billing.read'],
  '/dashboards/curve-abc': ['billing.read'],
  '/dashboards/multifilial': ['billing.read'],
  '/dashboards/financial': ['billing.read'],
  '/finance/timeline': ['billing.read'],
  '/finance/split': ['billing.read'],
  '/finance/card-machines': ['billing.read'],
  '/finance/split/simulator': ['billing.read'],
  '/finance/card-transactions': ['billing.read'],
  '/finance/split/export': ['billing.read'],
  '/finance/payment-enablement': ['payments.manage'],
  '/finance/payments-dashboard': ['billing.read'],
  '/payment-methods': ['billing.read'],
  '/cost-centers': ['billing.read'],
  '/expenses': ['billing.read'],
  '/cards': ['billing.read'],
  '/banks': ['billing.read'],
  '/pix': ['billing.read'],
  '/marketing/sms': ['marketing.read'],
  '/marketing/campaigns': ['marketing.read'],
  '/marketing/vaccine-email': ['marketing.read'],
  '/marketing/sms-settings': ['marketing.read'],
  '/notifications': ['notifications.read'],
  '/notifications/whatsapp': ['notifications.read'],
  '/users': ['users.read'],
  '/commission-calculations': ['staff.read'],
  '/staff': ['staff.read'],
  '/commission-rules': ['staff.read'],
  '/time-off': ['staff.read'],
  '/rh/professions': ['staff.read'],
  '/reports/audit/appointments': ['audit.read', 'scheduling.read'],
  '/reports/cash-drawer': ['billing.read'],
  '/reports/financial': ['billing.read'],
  '/reports/dre': ['billing.read'],
  '/reports/packages': ['billing.read', 'counter_sale.read'],
  '/reports/accounts-receivable': ['billing.read'],
  '/reports/received-accounts': ['billing.read'],
  '/reports/accounts-payable': ['billing.read'],
  '/reports/paid-accounts': ['billing.read'],
  '/reports/cheques': ['billing.read'],
  '/reports/advance-payments': ['billing.read'],
  '/reports/sales': ['billing.read', 'counter_sale.read'],
  '/reports/produced-items': ['billing.read', 'counter_sale.read'],
  '/reports/production': ['billing.read', 'counter_sale.read'],
  '/reports/appointments': ['scheduling.read'],
  '/reports/professional-care': ['billing.read', 'encounters.read'],
  '/reports/nf': ['billing.read', 'fiscal.read'],
  '/reports/registers/services': ['billing.read', 'service.read'],
  '/reports/registers/owners': ['billing.read', 'owners.read'],
  '/reports/registers/patients': ['billing.read', 'patients.read'],
  '/reports/registers/suppliers': ['billing.read', 'inventory.read'],
  '/reports/deleted-sales-counter-sales': ['billing.read', 'counter_sale.read'],
  '/reports/inventory': ['inventory.read'],
  '/reports/inventory-movements': ['inventory.read'],
  '/reports/inventory-invoices': ['inventory.read'],
  '/reports/inventory-products': ['inventory.read'],
  '/reports': ['billing.read'],
  '/reports/engine': ['billing.read'],
  '/administrative-reports': ['billing.read'],
  '/access-control': ['access.read'],
  '/audit': ['audit.read'],
  '/lgpd': ['lgpd.requests.read'],
  '/api-keys': ['api_keys.manage'],
  '/api-client': ['integrations.read'],
  '/webhooks': ['webhooks.read'],
  '/administration/settings': ['flags.admin'],
  '/master-search': ['owners.read', 'patients.read', 'product.read', 'counter_sale.read']
};

/** Legacy paths that must keep the same permission as their canonical route. */
export const navigationPermissionAliases: Readonly<Record<string, readonly string[]>> = {
  '/counter-sales': ['/comandas'],
  '/queue': ['/esteira', '/atendimento/esteira', '/atendimento/atendimentos/esteira'],
  '/reports/audit/appointments': ['/relatorios/auditoria/agendamentos'],
  '/reports/cash-drawer': ['/relatorios/financeiros/gaveta'],
  '/reports/financial': ['/relatorios/financeiros/fluxo-de-caixa'],
  '/reports/dre': ['/relatorios/financeiros/dre'],
  '/reports/packages': ['/relatorios/financeiros/pacotes'],
  '/reports/accounts-receivable': ['/relatorios/financeiros/contas-a-receber'],
  '/reports/received-accounts': ['/relatorios/financeiros/contas-recebidas'],
  '/reports/accounts-payable': ['/relatorios/financeiros/contas-a-pagar'],
  '/reports/paid-accounts': ['/relatorios/financeiros/contas-pagas'],
  '/reports/cheques': ['/relatorios/financeiros/cheques'],
  '/reports/advance-payments': ['/relatorios/financeiros/pagamento-antecipado'],
  '/reports/sales': ['/relatorios/atendimentos/comandas-vendas'],
  '/reports/produced-items': ['/relatorios/atendimentos/produtos-servicos-produzidos'],
  '/reports/production': ['/relatorios/atendimentos/producao'],
  '/reports/appointments': ['/relatorios/atendimentos/agenda'],
  '/reports/professional-care': ['/relatorios/atendimentos/atendimento-por-profissional'],
  '/reports/nf': ['/relatorios/personalizados/relatorio-de-nf-de-servicos-prestados'],
  '/reports/registers/services': ['/relatorios/cadastros/servicos'],
  '/reports/registers/owners': ['/relatorios/cadastros/clientes'],
  '/reports/registers/patients': ['/relatorios/cadastros/animais'],
  '/reports/registers/suppliers': ['/relatorios/cadastros/fornecedores'],
  '/reports/deleted-sales-counter-sales': ['/relatorios/cadastros/exclusao-de-vendas-e-comandas'],
  '/reports/inventory-movements': ['/relatorios/estoque/movimentacoes-no-estoque'],
  '/reports/inventory-invoices': ['/relatorios/estoque/entrada-de-nf'],
  '/reports/inventory-products': ['/relatorios/estoque/relatorio-de-produtos'],
  '/webhooks': ['/webhook', '/cadastro/webhooks', '/cadastros/webhooks']
};
