import { createHash, createHmac } from 'node:crypto';
import { mkdir, readFile, stat, unlink, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';

export interface FileStorageResult {
  readonly storageKey: string;
  readonly checksum: string;
  readonly sizeBytes: number;
}

export interface AttachmentDependencyHealth {
  readonly healthy: boolean;
  readonly provider: string;
  readonly detail: string;
}

export interface AttachmentDependencyHealthCheckOptions {
  readonly signal?: AbortSignal;
}

export interface FileStorageOperationOptions {
  /** Cancels the provider request when the enclosing operation is abandoned. */
  readonly signal?: AbortSignal;
  /** Per-operation deadline. Defaults to the adapter request timeout. */
  readonly timeoutMs?: number;
}

export interface FileStorage {
  /** True only for private, externally durable storage suitable for production. */
  readonly productionReady?: boolean;
  /** Safe, read-only reachability probe used by production readiness. */
  healthCheck?(
    options?: AttachmentDependencyHealthCheckOptions
  ): Promise<AttachmentDependencyHealth>;
  store(
    accountId: string,
    linkedEntityId: string,
    fileName: string,
    content: Buffer,
    options?: FileStorageOperationOptions
  ): Promise<FileStorageResult>;
  retrieve(
    accountId: string,
    storageKey: string,
    options?: FileStorageOperationOptions
  ): Promise<Buffer | null>;
  delete(
    accountId: string,
    storageKey: string,
    options?: FileStorageOperationOptions
  ): Promise<boolean>;
  exists(
    accountId: string,
    storageKey: string,
    options?: FileStorageOperationOptions
  ): Promise<boolean>;
}

const SAFE_STORAGE_SEGMENT = /^[A-Za-z0-9_-]+$/;
const STORAGE_NAMESPACES = new Set(['local', 'pending']);

function requireSafeStorageSegment(value: string, fieldName: string): string {
  const normalized = value.trim();
  if (!SAFE_STORAGE_SEGMENT.test(normalized)) {
    throw new Error(`Invalid attachment storage ${fieldName}`);
  }
  return normalized;
}

function isSafeStorageAccountId(value: string): boolean {
  return SAFE_STORAGE_SEGMENT.test(value) && !STORAGE_NAMESPACES.has(value);
}

function requireSafeStorageAccountId(value: string): string {
  const normalized = value.trim();
  if (normalized !== value || !isSafeStorageAccountId(normalized)) {
    throw new Error('Invalid attachment storage accountId');
  }
  return normalized;
}

/**
 * Accept only keys generated by this module and bound to the requested tenant.
 * Direct provider keys use `{account}/{entity}/...`; local and pending keys
 * use `{namespace}/{account}/{entity}/...`.
 */
export function isTenantScopedStorageKey(accountId: string, storageKey: string): boolean {
  if (!isSafeStorageAccountId(accountId) || !storageKey || storageKey.includes('\0')) {
    return false;
  }
  const segments = storageKey.split('/');
  if (
    segments.some(
      (segment) => !segment || segment === '.' || segment === '..' || segment.includes('\\')
    )
  ) {
    return false;
  }

  return (
    (segments.length >= 3 && segments[0] === accountId) ||
    (segments.length >= 4 && STORAGE_NAMESPACES.has(segments[0] ?? '') && segments[1] === accountId)
  );
}

export interface LocalFileStorageOptions {
  readonly basePath: string;
}

export class LocalFileStorage implements FileStorage {
  public readonly productionReady = false;
  readonly #basePath: string;

  public constructor(options: LocalFileStorageOptions) {
    this.#basePath = resolve(options.basePath);
  }

  public async healthCheck(): Promise<AttachmentDependencyHealth> {
    return {
      healthy: true,
      provider: 'local-filesystem',
      detail: 'Local attachment storage is reachable.'
    };
  }

  #safePath(storageKey: string): string | null {
    if (!storageKey || storageKey.includes('\0')) return null;
    const fullPath = resolve(this.#basePath, storageKey);
    const pathFromBase = relative(this.#basePath, fullPath);
    if (pathFromBase.startsWith('..') || pathFromBase.includes(`..${String.fromCharCode(47)}`)) {
      return null;
    }
    return fullPath;
  }

  public async store(
    accountId: string,
    linkedEntityId: string,
    fileName: string,
    content: Buffer
  ): Promise<FileStorageResult> {
    const checksum = createHash('sha256').update(content).digest('hex');
    const sizeBytes = content.length;
    const safeName = fileName.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 180) || 'unnamed';
    const safeAccountId = requireSafeStorageAccountId(accountId);
    const safeLinkedEntityId = requireSafeStorageSegment(linkedEntityId, 'linkedEntityId');
    const safeStorageKey = `${safeAccountId}/${safeLinkedEntityId}/${checksum.slice(0, 12)}_${safeName}`;
    const storageKey = safeStorageKey;
    if (!isTenantScopedStorageKey(accountId, storageKey)) {
      throw new Error('Invalid attachment storage key');
    }
    const fullPath = this.#safePath(safeStorageKey);
    if (!fullPath) throw new Error('Invalid attachment storage path');

    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, content);

    return { storageKey: safeStorageKey, checksum, sizeBytes };
  }

  public async retrieve(accountId: string, storageKey: string): Promise<Buffer | null> {
    if (!isTenantScopedStorageKey(accountId, storageKey)) return null;
    const fullPath = this.#safePath(storageKey);
    if (!fullPath) return null;
    try {
      return await readFile(fullPath);
    } catch {
      return null;
    }
  }

  public async delete(accountId: string, storageKey: string): Promise<boolean> {
    if (!isTenantScopedStorageKey(accountId, storageKey)) return false;
    const fullPath = this.#safePath(storageKey);
    if (!fullPath) return false;
    try {
      await unlink(fullPath);
      return true;
    } catch {
      return false;
    }
  }

  public async exists(accountId: string, storageKey: string): Promise<boolean> {
    if (!isTenantScopedStorageKey(accountId, storageKey)) return false;
    const fullPath = this.#safePath(storageKey);
    if (!fullPath) return false;
    try {
      await stat(fullPath);
      return true;
    } catch {
      return false;
    }
  }
}

export interface S3CompatibleFileStorageOptions {
  readonly endpoint: string;
  readonly bucket: string;
  readonly accessKeyId: string;
  readonly secretAccessKey: string;
  readonly region?: string;
  readonly pathStyle?: boolean;
  readonly healthCheckTimeoutMs?: number;
  readonly requestTimeoutMs?: number;
}

interface S3Response {
  readonly ok: boolean;
  readonly status: number;
  readonly body?: Buffer;
}

function requirePositiveTimeout(value: number, fieldName: string): number {
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${fieldName} must be a positive integer`);
  }
  return value;
}

function createAbortDeadline(
  timeoutMs: number,
  parentSignal?: AbortSignal
): {
  readonly signal: AbortSignal;
  readonly elapsed: Promise<never>;
  cleanup(): void;
} {
  const controller = new AbortController();
  let timeoutHandle: ReturnType<typeof setTimeout> | undefined;
  let rejectElapsed!: (reason: Error) => void;
  let aborted = false;
  const elapsed = new Promise<never>((_resolve, reject) => {
    rejectElapsed = reject;
  });
  const abort = (message: string): void => {
    if (aborted) return;
    aborted = true;
    const error = new Error(message);
    controller.abort(error);
    rejectElapsed(error);
  };
  const onParentAbort = (): void => abort('S3 request cancelled');

  if (parentSignal?.aborted) {
    abort('S3 request cancelled');
  } else {
    parentSignal?.addEventListener('abort', onParentAbort, { once: true });
    timeoutHandle = setTimeout(() => abort('S3 request timed out'), timeoutMs);
    timeoutHandle.unref?.();
  }

  return {
    signal: controller.signal,
    elapsed,
    cleanup() {
      if (timeoutHandle) clearTimeout(timeoutHandle);
      parentSignal?.removeEventListener('abort', onParentAbort);
    }
  };
}

function hmac(key: Buffer | string, value: string): Buffer {
  return createHmac('sha256', key).update(value, 'utf8').digest();
}

function awsEncode(value: string): string {
  return encodeURIComponent(value).replace(/%2F/g, '/');
}

function sha256(value: Buffer | string): string {
  return createHash('sha256').update(value).digest('hex');
}

/**
 * Private S3-compatible object storage adapter. It uses SigV4 directly so the
 * API does not need a cloud SDK and works with AWS S3, MinIO and compatible
 * gateways. No public URL is ever returned; downloads remain authorization
 * checked by the API route.
 */
export class S3CompatibleFileStorage implements FileStorage {
  public readonly productionReady = true;
  readonly #endpoint: URL;
  readonly #bucket: string;
  readonly #accessKeyId: string;
  readonly #secretAccessKey: string;
  readonly #region: string;
  readonly #pathStyle: boolean;
  readonly #healthCheckTimeoutMs: number;
  readonly #requestTimeoutMs: number;

  public constructor(options: S3CompatibleFileStorageOptions) {
    this.#endpoint = new URL(options.endpoint);
    if (this.#endpoint.protocol !== 'http:' && this.#endpoint.protocol !== 'https:') {
      throw new Error('S3 endpoint must use http or https');
    }
    this.#bucket = options.bucket.trim();
    this.#accessKeyId = options.accessKeyId.trim();
    this.#secretAccessKey = options.secretAccessKey;
    this.#region = options.region?.trim() || 'us-east-1';
    this.#pathStyle = options.pathStyle ?? true;
    this.#healthCheckTimeoutMs = requirePositiveTimeout(
      options.healthCheckTimeoutMs ?? 1_000,
      'S3 health check timeout'
    );
    this.#requestTimeoutMs = requirePositiveTimeout(
      options.requestTimeoutMs ?? 30_000,
      'S3 request timeout'
    );
    if (!this.#bucket || !this.#accessKeyId || !this.#secretAccessKey) {
      throw new Error('S3 bucket and credentials are required');
    }
  }

  /**
   * Verifies authenticated bucket reachability without creating, listing, or
   * deleting any object. HEAD bucket is supported by S3 and MinIO and is safe
   * to execute on every readiness poll.
   */
  public async healthCheck(
    options: AttachmentDependencyHealthCheckOptions = {}
  ): Promise<AttachmentDependencyHealth> {
    try {
      const response = await this.#request(
        'HEAD',
        undefined,
        undefined,
        {},
        {
          signal: options.signal,
          timeoutMs: this.#healthCheckTimeoutMs
        }
      );
      return response.ok
        ? {
            healthy: true,
            provider: 's3',
            detail: 'Private attachment bucket is reachable.'
          }
        : {
            healthy: false,
            provider: 's3',
            detail: 'Private attachment bucket is unavailable.'
          };
    } catch {
      return {
        healthy: false,
        provider: 's3',
        detail: 'Private attachment bucket is unavailable.'
      };
    }
  }

  public async store(
    accountId: string,
    linkedEntityId: string,
    fileName: string,
    content: Buffer,
    options: FileStorageOperationOptions = {}
  ): Promise<FileStorageResult> {
    const checksum = sha256(content);
    const safeName = fileName.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 180) || 'unnamed';
    const safeAccountId = requireSafeStorageAccountId(accountId);
    const safeLinkedEntityId = requireSafeStorageSegment(linkedEntityId, 'linkedEntityId');
    const storageKey = `${safeAccountId}/${safeLinkedEntityId}/${checksum.slice(0, 12)}_${safeName}`;
    if (!isTenantScopedStorageKey(accountId, storageKey)) {
      throw new Error('Invalid attachment storage key');
    }
    const response = await this.#request(
      'PUT',
      storageKey,
      content,
      {
        'content-type': 'application/octet-stream'
      },
      options
    );
    if (!response.ok) {
      throw new Error(`S3 object upload failed with status ${response.status}`);
    }
    return { storageKey, checksum, sizeBytes: content.length };
  }

  public async retrieve(
    accountId: string,
    storageKey: string,
    options: FileStorageOperationOptions = {}
  ): Promise<Buffer | null> {
    if (!isTenantScopedStorageKey(accountId, storageKey)) return null;
    const response = await this.#request('GET', storageKey, undefined, {}, options, true);
    if (response.status === 404) return null;
    if (!response.ok) throw new Error(`S3 object download failed with status ${response.status}`);
    return response.body ?? Buffer.alloc(0);
  }

  public async delete(
    accountId: string,
    storageKey: string,
    options: FileStorageOperationOptions = {}
  ): Promise<boolean> {
    if (!isTenantScopedStorageKey(accountId, storageKey)) return false;
    const response = await this.#request('DELETE', storageKey, undefined, {}, options);
    if (response.status === 404) return false;
    if (!response.ok) throw new Error(`S3 object deletion failed with status ${response.status}`);
    return true;
  }

  public async exists(
    accountId: string,
    storageKey: string,
    options: FileStorageOperationOptions = {}
  ): Promise<boolean> {
    if (!isTenantScopedStorageKey(accountId, storageKey)) return false;
    const response = await this.#request('HEAD', storageKey, undefined, {}, options);
    if (response.status === 404) return false;
    if (!response.ok) throw new Error(`S3 object check failed with status ${response.status}`);
    return true;
  }

  async #request(
    method: 'GET' | 'PUT' | 'DELETE' | 'HEAD',
    storageKey?: string,
    body?: Buffer,
    extraHeaders: Record<string, string> = {},
    options: FileStorageOperationOptions = {},
    consumeBody = false
  ): Promise<S3Response> {
    const now = new Date();
    const amzDate = now
      .toISOString()
      .replace(/[:-]|\.\d{3}/g, '')
      .replace(/Z$/, 'Z');
    const shortDate = amzDate.slice(0, 8);
    const payloadHash = sha256(body ?? Buffer.alloc(0));
    const host = this.#endpoint.host;
    const encodedKey = storageKey?.split('/').map(awsEncode).join('/');
    const endpointPath = this.#endpoint.pathname.replace(/\/$/, '');
    const path = this.#pathStyle
      ? `${endpointPath}/${awsEncode(this.#bucket)}${encodedKey ? `/${encodedKey}` : ''}`
      : `${endpointPath}${encodedKey ? `/${encodedKey}` : ''}`;
    const url = new URL(this.#endpoint.toString());
    if (!this.#pathStyle) url.hostname = `${this.#bucket}.${url.hostname}`;
    url.pathname = path || '/';

    const headers: Record<string, string> = {
      host: url.host,
      'x-amz-content-sha256': payloadHash,
      'x-amz-date': amzDate,
      ...extraHeaders
    };
    const canonicalHeaders = Object.keys(headers)
      .map((name) => name.toLowerCase())
      .sort()
      .map((name) => `${name}:${headers[name].trim().replace(/\s+/g, ' ')}\n`)
      .join('');
    const signedHeaders = Object.keys(headers)
      .map((name) => name.toLowerCase())
      .sort()
      .join(';');
    const canonicalRequest = [
      method,
      path || '/',
      '',
      canonicalHeaders,
      signedHeaders,
      payloadHash
    ].join('\n');
    const scope = `${shortDate}/${this.#region}/s3/aws4_request`;
    const stringToSign = ['AWS4-HMAC-SHA256', amzDate, scope, sha256(canonicalRequest)].join('\n');
    const signingKey = hmac(
      hmac(hmac(hmac(`AWS4${this.#secretAccessKey}`, shortDate), this.#region), 's3'),
      'aws4_request'
    );
    const signature = createHmac('sha256', signingKey).update(stringToSign).digest('hex');
    headers.authorization =
      `AWS4-HMAC-SHA256 Credential=${this.#accessKeyId}/${scope}, ` +
      `SignedHeaders=${signedHeaders}, Signature=${signature}`;

    const timeoutMs = requirePositiveTimeout(
      options.timeoutMs ?? this.#requestTimeoutMs,
      'S3 operation timeout'
    );
    const deadline = createAbortDeadline(timeoutMs, options.signal);
    let response: Response | undefined;
    const operation = (async (): Promise<S3Response> => {
      response = await fetch(url, {
        method,
        headers,
        body: body ?? undefined,
        signal: deadline.signal
      });
      const responseBody =
        consumeBody && response.ok ? Buffer.from(await response.arrayBuffer()) : undefined;
      return { ok: response.ok, status: response.status, body: responseBody };
    })();

    try {
      return await Promise.race([operation, deadline.elapsed]);
    } finally {
      deadline.cleanup();
      if (response?.body && !response.bodyUsed) {
        void response.body.cancel().catch(() => undefined);
      }
    }
  }
}

export function createMemoryFileStorage(): FileStorage {
  const store = new Map<string, Buffer>();

  return {
    productionReady: false,
    async healthCheck() {
      return {
        healthy: true,
        provider: 'memory',
        detail: 'In-memory attachment storage is reachable.'
      };
    },
    async store(accountId, linkedEntityId, fileName, content) {
      const checksum = createHash('sha256').update(content).digest('hex');
      const sizeBytes = content.length;
      const safeName = fileName.replace(/[^a-zA-Z0-9._-]/g, '_');
      const safeAccountId = requireSafeStorageAccountId(accountId);
      const safeLinkedEntityId = requireSafeStorageSegment(linkedEntityId, 'linkedEntityId');
      const storageKey = `${safeAccountId}/${safeLinkedEntityId}/${checksum.slice(0, 12)}_${safeName}`;
      if (!isTenantScopedStorageKey(accountId, storageKey)) {
        throw new Error('Invalid attachment storage key');
      }
      store.set(storageKey, Buffer.from(content));
      return { storageKey, checksum, sizeBytes };
    },
    async retrieve(accountId, storageKey) {
      if (!isTenantScopedStorageKey(accountId, storageKey)) return null;
      const content = store.get(storageKey);
      return content ? Buffer.from(content) : null;
    },
    async delete(accountId, storageKey) {
      if (!isTenantScopedStorageKey(accountId, storageKey)) return false;
      return store.delete(storageKey);
    },
    async exists(accountId, storageKey) {
      if (!isTenantScopedStorageKey(accountId, storageKey)) return false;
      return store.has(storageKey);
    }
  };
}
