export function renderEncounters(): string {
  const html = [
    '<div class="card">',
    '<div class="tab-bar">',
    '<button class="tab-btn active" data-tab="fila">Fila</button>',
    '<button class="tab-btn" data-tab="atendimentos">Atendimentos</button>',
    '<button class="tab-btn" data-tab="triagem">Triagem</button>',
    '</div>',

    '<div id="tab-fila" class="tab-content active">',
    '<h2>Fila de Espera</h2>',
    '<div class="btn-row">',
    '<button class="btn btn-primary" id="show-checkin-form">Novo Check-in</button>',
    '</div>',
    '<div id="checkin-form" class="form hidden">',
    '<h3>Check-in</h3>',
    '<div class="grid grid-2">',
    '<div><label>ID do Paciente</label><input type="text" id="checkin-patient-id" placeholder="ID do paciente"></div>',
    '<div><label>ID do Tutor</label><input type="text" id="checkin-owner-id" placeholder="ID do tutor"></div>',
    '</div>',
    '<div><label>Motivo</label><input type="text" id="checkin-motivo" placeholder="Motivo da visita"></div>',
    '<div class="btn-row">',
    '<button class="btn btn-primary" id="submit-checkin">Confirmar Check-in</button>',
    '<button class="btn btn-secondary" id="cancel-checkin">Cancelar</button>',
    '</div>',
    '</div>',
    '<table class="table" id="queue-table">',
    '<thead><tr><th>Paciente</th><th>Tutor</th><th>Motivo</th><th>Prioridade</th><th>Status</th><th>Ações</th></tr></thead>',
    '<tbody id="queue-tbody"></tbody>',
    '</table>',
    '</div>',

    '<div id="tab-atendimentos" class="tab-content">',
    '<h2>Atendimentos</h2>',
    '<div class="btn-row">',
    '<button class="btn btn-primary" id="show-encounter-form">Abrir Atendimento</button>',
    '</div>',
    '<div id="encounter-form" class="form hidden">',
    '<h3>Novo Atendimento</h3>',
    '<div class="grid grid-2">',
    '<div><label>ID do Paciente</label><input type="text" id="encounter-patient-id" placeholder="ID do paciente"></div>',
    '<div><label>ID do Tutor</label><input type="text" id="encounter-owner-id" placeholder="ID do tutor"></div>',
    '</div>',
    '<div><label>Motivo</label><input type="text" id="encounter-motivo" placeholder="Motivo da visita"></div>',
    '<div class="btn-row">',
    '<button class="btn btn-primary" id="submit-encounter">Abrir</button>',
    '<button class="btn btn-secondary" id="cancel-encounter">Cancelar</button>',
    '</div>',
    '</div>',
    '<table class="table" id="encounters-table">',
    '<thead><tr><th>ID</th><th>Paciente</th><th>Tutor</th><th>Status</th><th>Aberto em</th><th>Ações</th></tr></thead>',
    '<tbody id="encounters-tbody"></tbody>',
    '</table>',
    '</div>',

    '<div id="tab-triagem" class="tab-content">',
    '<h3>Triagem</h3>',
    '<div class="form">',
    '<div class="grid grid-2">',
    '<div><label>ID do Atendimento</label><input type="text" id="triage-encounter-id" placeholder="ID do atendimento"></div>',
    '<div><label>ID do Paciente</label><input type="text" id="triage-patient-id" placeholder="ID do paciente"></div>',
    '</div>',
    '<div><label>Queixa Principal</label><input type="text" id="triage-complaint" placeholder="Queixa principal"></div>',
    '<div class="grid grid-2">',
    '<div><label>Prioridade</label><select id="triage-priority">',
    '<option value="">Selecione</option>',
    '<option value="low">Baixa</option>',
    '<option value="medium">Média</option>',
    '<option value="high">Alta</option>',
    '<option value="emergency">Emergência</option>',
    '</select></div>',
    '<div><label>Alertas (separados por vírgula)</label><input type="text" id="triage-alerts" placeholder="Alerta 1, Alerta 2"></div>',
    '</div>',
    '<div class="btn-row">',
    '<button class="btn btn-primary" id="submit-triage">Registrar Triagem</button>',
    '</div>',
    '</div>',
    '<h4>Triagens Recentes</h4>',
    '<table class="table" id="triage-table">',
    '<thead><tr><th>ID</th><th>Paciente</th><th>Queixa</th><th>Prioridade</th><th>Data</th></tr></thead>',
    '<tbody id="triage-tbody"></tbody>',
    '</table>',
    '</div>',
    '</div>',

    '<div id="alert-container"></div>',

    '<script>',
    '(function() {',
    'var apiRequest = window.apiRequest || function(url, opts) { return fetch(url, opts || {}).then(function(r) { return r.json(); }); };',
    'var escapeHtml = window.escapeHtml || function(s) { return s; };',
    'var formatDate = window.formatDate || function(d) { return new Date(d).toLocaleString("pt-BR"); };',

    'function showAlert(msg, isErr) {',
    'var c = document.getElementById("alert-container");',
    'var a = document.createElement("div");',
    'a.className = isErr ? "alert-error" : "alert-success";',
    'a.textContent = msg;',
    'c.appendChild(a);',
    'setTimeout(function() { a.remove(); }, 5000);',
    '}',

    'function getBadge(status) {',
    'var m = {"open":"<span class=badge badge-success>Aberto</span>","in_triage":"<span class=badge badge-warning>Em Triagem</span>","in_care":"<span class=badge badge-info>Em Atendimento</span>","closed":"<span class=badge badge-neutral>Fechado</span>"};',
    'return m[status] || "<span class=badge>" + escapeHtml(status) + "</span>";',
    '}',

    'document.querySelectorAll(".tab-btn").forEach(function(b) {',
    'b.addEventListener("click", function() {',
    'document.querySelectorAll(".tab-btn").forEach(function(x) { x.classList.remove("active"); });',
    'document.querySelectorAll(".tab-content").forEach(function(x) { x.classList.remove("active"); });',
    'this.classList.add("active");',
    'document.getElementById("tab-" + this.dataset.tab).classList.add("active");',
    'if (this.dataset.tab === "fila") loadQueue();',
    'if (this.dataset.tab === "atendimentos") loadEncounters();',
    'if (this.dataset.tab === "triagem") loadTriagens();',
    '});',
    '});',

    'document.getElementById("show-checkin-form").addEventListener("click", function() {',
    'document.getElementById("checkin-form").classList.remove("hidden");',
    '});',

    'document.getElementById("cancel-checkin").addEventListener("click", function() {',
    'document.getElementById("checkin-form").classList.add("hidden");',
    'document.getElementById("checkin-patient-id").value = "";',
    'document.getElementById("checkin-owner-id").value = "";',
    'document.getElementById("checkin-motivo").value = "";',
    '});',

    'document.getElementById("submit-checkin").addEventListener("click", function() {',
    'var pi = document.getElementById("checkin-patient-id").value;',
    'var oi = document.getElementById("checkin-owner-id").value;',
    'var m = document.getElementById("checkin-motivo").value;',
    'if (!pi || !oi) { showAlert("Preencha todos os campos obrigatorios", true); return; }',
    'apiRequest("/queue/check-in", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({patientId: pi, ownerId: oi, motivo: m})}).then(function() { showAlert("Check-in realizado com sucesso"); document.getElementById("cancel-checkin").click(); loadQueue(); }).catch(function() { showAlert("Erro ao realizar check-in", true); });',
    '});',

    'function loadQueue() {',
    'apiRequest("/queue").then(function(q) {',
    'var tb = document.getElementById("queue-tbody");',
    'tb.innerHTML = q.map(function(e) { var btn = "<button class=btn btn-sm btn-primary data-call=\\"" + e.id + "\\">Chamar</button>"; return "<tr><td>" + escapeHtml(e.patientName || e.patientId) + "</td><td>" + escapeHtml(e.ownerName || e.ownerId) + "</td><td>" + escapeHtml(e.motivo || "-") + "</td><td>" + escapeHtml(e.prioridade || "-") + "</td><td>" + escapeHtml(e.status) + "</td><td>" + btn + "</td></tr>"; }).join("");',
    'tb.querySelectorAll("[data-call]").forEach(function(btn) {',
    'btn.addEventListener("click", function() {',
    'apiRequest("/queue/" + btn.dataset.call + "/call", {method: "POST"}).then(function() { showAlert("Paciente chamado"); loadQueue(); }).catch(function() { showAlert("Erro ao chamar paciente", true); });',
    '});',
    '});',
    '}).catch(function() { document.getElementById("queue-tbody").innerHTML = "<tr><td colspan=6>Erro ao carregar fila</td></tr>"; });',
    '}',

    'document.getElementById("show-encounter-form").addEventListener("click", function() {',
    'document.getElementById("encounter-form").classList.remove("hidden");',
    '});',

    'document.getElementById("cancel-encounter").addEventListener("click", function() {',
    'document.getElementById("encounter-form").classList.add("hidden");',
    'document.getElementById("encounter-patient-id").value = "";',
    'document.getElementById("encounter-owner-id").value = "";',
    'document.getElementById("encounter-motivo").value = "";',
    '});',

    'document.getElementById("submit-encounter").addEventListener("click", function() {',
    'var pi = document.getElementById("encounter-patient-id").value;',
    'var oi = document.getElementById("encounter-owner-id").value;',
    'var m = document.getElementById("encounter-motivo").value;',
    'if (!pi || !oi) { showAlert("Preencha todos os campos obrigatorios", true); return; }',
    'apiRequest("/encounters", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({patientId: pi, ownerId: oi, motivo: m})}).then(function() { showAlert("Atendimento aberto com sucesso"); document.getElementById("cancel-encounter").click(); loadEncounters(); }).catch(function() { showAlert("Erro ao abrir atendimento", true); });',
    '});',

    'function loadEncounters() {',
    'apiRequest("/encounters").then(function(list) {',
    'var tb = document.getElementById("encounters-tbody");',
    'tb.innerHTML = list.map(function(enc) {',
    'var acts = "";',
    'if (enc.status !== "closed") {',
    'acts = "<button class=btn btn-sm btn-primary data-transition=\\"" + enc.id + "\\">Transicao</button><button class=btn btn-sm btn-secondary data-close=\\"" + enc.id + "\\">Fechar</button>";',
    '}',
    'acts += "<button class=btn btn-sm btn-info data-timeline=\\"" + enc.id + "\\">Timeline</button>";',
    'return "<tr><td>" + enc.id + "</td><td>" + escapeHtml(enc.patientName || enc.patientId) + "</td><td>" + escapeHtml(enc.ownerName || enc.ownerId) + "</td><td>" + getBadge(enc.status) + "</td><td>" + formatDate(enc.createdAt) + "</td><td>" + acts + "</td></tr>";',
    '}).join("");',
    'tb.querySelectorAll("[data-transition]").forEach(function(b) { b.addEventListener("click", function() { apiRequest("/encounters/" + b.dataset.transition + "/transition", {method: "POST"}).then(function() { showAlert("Status atualizado"); loadEncounters(); }).catch(function() { showAlert("Erro ao atualizar status", true); }); }); });',
    'tb.querySelectorAll("[data-close]").forEach(function(b) { b.addEventListener("click", function() { apiRequest("/encounters/" + b.dataset.close + "/close", {method: "POST"}).then(function() { showAlert("Atendimento fechado"); loadEncounters(); }).catch(function() { showAlert("Erro ao fechar atendimento", true); }); }); });',
    'tb.querySelectorAll("[data-timeline]").forEach(function(b) { b.addEventListener("click", function() { window.location.href = "/encounters/" + b.dataset.timeline; }); });',
    '}).catch(function() { document.getElementById("encounters-tbody").innerHTML = "<tr><td colspan=6>Erro ao carregar atendimentos</td></tr>"; });',
    '}',

    'document.getElementById("submit-triage").addEventListener("click", function() {',
    'var ei = document.getElementById("triage-encounter-id").value;',
    'var pi = document.getElementById("triage-patient-id").value;',
    'var cq = document.getElementById("triage-complaint").value;',
    'var pr = document.getElementById("triage-priority").value;',
    'var al = document.getElementById("triage-alerts").value;',
    'if (!ei || !pi || !cq) { showAlert("Preencha todos os campos obrigatorios", true); return; }',
    'apiRequest("/triage", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({encounterId: ei, patientId: pi, complaint: cq, priority: pr, alerts: al})}).then(function() { showAlert("Triagem registrada com sucesso"); document.getElementById("triage-encounter-id").value = ""; document.getElementById("triage-patient-id").value = ""; document.getElementById("triage-complaint").value = ""; document.getElementById("triage-priority").value = ""; document.getElementById("triage-alerts").value = ""; loadTriagens(); }).catch(function() { showAlert("Erro ao registrar triagem", true); });',
    '});',

    'function loadTriagens() {',
    'apiRequest("/triage").then(function(list) {',
    'var tb = document.getElementById("triage-tbody");',
    'tb.innerHTML = list.map(function(t) { return "<tr><td>" + t.id + "</td><td>" + escapeHtml(t.patientName || t.patientId) + "</td><td>" + escapeHtml(t.complaint) + "</td><td>" + escapeHtml(t.priority) + "</td><td>" + formatDate(t.createdAt) + "</td></tr>"; }).join("");',
    '}).catch(function() { document.getElementById("triage-tbody").innerHTML = "<tr><td colspan=5>Erro ao carregar triagens</td></tr>"; });',
    '}',

    'loadQueue();',
    '})();',
    '</scr' + 'ipt>'
  ];

  return html.join('');
}
